name: Generate Datas

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # 1. Cria a animação da cobrinha
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: NadiaMonfardini # <-- Seu nome de usuário
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # 2. Publica o arquivo SVG gerado
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output # Onde o arquivo SVG será salvo
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
